### PR TITLE
add manpages for all commands

### PR DESCRIPTION
**Pull request by morxa**
The manpages are created from the README.

### CODE REVIEW

**Comment by masc3d** [comment]
could generation be integrated into setup.py so manpages are included within distribution without adding them to git explicitly?

**Comment by morxa** [comment]
I tried different methods to autogenerate the manpages (`rst2man` and `help2man`), but none of the results were satisfying. `rst2man` does not work because the README is not really in manpage format. `help2man` does not support subcommands, i.e. I cannot generate different manpages for `init` and `update` and it would only include the help text from the main executable without a command, which is insufficient.

So the manpages are hand-edited and not generated. This is not ideal, but it seemed like the only working solution.

**Comment by masc3d** [comment]
`rst2man` converts from reStructured text so it should basically work with the README.rst?

**Comment by masc3d** [comment]
I suppose it could be integrated with classes attached to [this issue](https://bugs.python.org/issue14102) or another solution would be to use [sphinx](http://www.sphinx-doc.org/en/stable/index.html). I won't merge another layer of manually maintained documentation.

**Comment by masc3d** [comment]
See #26

**Pull request closed without merging**
