### PR TITLE
Merge automatic generation of man pages

### PR DESCRIPTION
**Pull request by syntonym**
Hooks into the `sdist` comman to automatically create man pages from the argument parser. Then uses a short script `btrfs_sxbackup_make_doc.py` to create a scaffold for sphinxcontrib.autoprogram to fill in. Then use sphinx to actually generate the man pages. Because all of this is automatically done, any command available from the parser gets its own man page, even if new one will be added in the future.

### CODE REVIEW

**Comment by syntonym** [comment]
Fixes #26

**Comment by masc3d** [comment]
did some basic tests, the generation works, that's nice. still needs some cleanup but I can take care of that. As sphinx is python I wondered if it's possible to skip the make toolchain and integrate directly?

**Comment by syntonym** [comment]
> still needs some cleanup but I can take care of that.

For small things you are probably faster yourself, but if you describe it to me I can try to meet your criterias. 

> I wondered if it's possible to skip the make toolchain and integrate directly?

done

**Comment by masc3d** [comment]
I merged this manually on branch `setup-sphinx` for now and will finalize integration there.

**Pull request closed without merging**
