### PR TITLE
Do not use btrfs send and receive when source and destination are on the same btrfs filesystem

### PR DESCRIPTION
**Pull request by tytgatlieven**
This allows the source and destination to be on the same btrfs filesystem.
It keeps the operation identical as possible regular btrfs-sxbackup
The major difference is in Location.transfer_btrfs_snapshot().
transfer_btrfs_snapshot does not use btrfs send/receive whe identical_filesystem is enabled.
It simply takes a new snapshot of the source snapshot.

identical_filesystem is enabled as follows:
btrfs-sxbackup --identical_filesystem

### CODE REVIEW

**Comment by masc3d** [comment]
is it possible to implement this without adding additional option, eg detect during runtime?

**Comment by tytgatlieven** [comment]
This was indeed my original idea, but I didn't figure out how to get there. so I used the flag instead.
I believe we should find a way to figure out the UUID of the current btrfs filesystem the source and destination snapshots are in. I did not yet find out how to do that.
If that is solved, changing the code in the transfer_btrfs_snapshot is not a big deal.
Any idea how to do that?

**Comment by masc3d** [comment]
`btrfs fi show <path>` uuid would do the trick I suppose

**Comment by masc3d** [comment]
if you go this route and parse regex, please follow `entities.py`, eg new class `Filesystem`

**Comment by tytgatlieven** [comment]
It was not that simple ;-)
btrfs fi show <path> apparently needs the mount point of the btrfs volume, not a subdir or a subvolume.
Hence I scan recursively the parent dir from the base dir.

It falls back to regular mode in case something goes wrong in the detection of the btrfs uuid.
(I do rely on output behaviour of btrfs.)

I checked it's operation on:
* local system with identical filesystem
* remote system with identical filesystem
* toplevel subvol and lower level subvol on remote host
* non-identical hosts
* different btrfs filesystems on the same host

However, please verify on your system before merging this.

**Comment by tytgatlieven** [comment]
build_path() apparently got called with None as argument.
I'll check all my backups tomorrow morning and let you know if they are ok.

**Comment by tytgatlieven** [comment]
It seams everything is ok now. So this should be ready for merger.
@masc3d :Ask if there is anything you need from me!

**Comment by masc3d** [comment]
yes, looking good @tytgatlieven

**Comment by masc3d** [comment]
on second glance, it would be better to have `identical_filesystem` runtime only instead persistent via `JobLocation`.

**Comment by tytgatlieven** [comment]
I did consider this. However, the scan can take a bit of time since it needs a recursive call to btrfs tool, which is then executed remotely. So, I would propose to only do this in case a faster way is found to do the detection of an identical underlying filesystem.

**Comment by tytgatlieven** [comment]
PS: Did you check the version string of sxbackup?

**Pull request merged**
